-- Supabase / Postgres schema for CampusFriend posts
-- Features: posts, hashtags, hearts (likes), comments, user profiles, timestamps
-- Notes:
-- - This design assumes you will use Supabase Auth (auth.users) for user identity.
-- - Client apps must use anon/public key + user auth session for writes when RLS is enabled.

-- Extensions
create extension if not exists pgcrypto;

-- Utility: updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =====================
--  Profiles (user info)
-- =====================
-- Store app-level profile fields. Auth email/password live in auth.users.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  avatar_url text,
  department text,
  year smallint check (year between 1 and 8),
  hobbies text[] not null default '{}'::text[],
  courses text[] not null default '{}'::text[],
  bio text not null default '' check (char_length(bio) <= 280),

  -- Optional: helps migrate from current mock ids like "user-1"
  legacy_user_id text unique,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create index if not exists profiles_department_idx on public.profiles (department);
create index if not exists profiles_hobbies_gin on public.profiles using gin (hobbies);
create index if not exists profiles_courses_gin on public.profiles using gin (courses);

-- ============
--  Posts
-- ============
create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),

  -- Optional: for migrating from mock ids like "post-123"
  legacy_post_id text unique,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

create index if not exists posts_author_created_idx on public.posts (author_id, created_at desc);
create index if not exists posts_created_idx on public.posts (created_at desc);

-- ==================
--  Hashtags
-- ==================
create table if not exists public.hashtags (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 64),
  created_at timestamptz not null default now()
);

-- Case-insensitive uniqueness (good enough for latin hashtags)
create unique index if not exists hashtags_name_lower_uq on public.hashtags (lower(name));

create table if not exists public.post_hashtags (
  post_id uuid not null references public.posts(id) on delete cascade,
  hashtag_id bigint not null references public.hashtags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, hashtag_id)
);

create index if not exists post_hashtags_hashtag_idx on public.post_hashtags (hashtag_id);
create index if not exists post_hashtags_post_idx on public.post_hashtags (post_id);

-- ============
--  Hearts (likes)
-- ============
create table if not exists public.post_likes (
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index if not exists post_likes_post_idx on public.post_likes (post_id);
create index if not exists post_likes_user_idx on public.post_likes (user_id);

-- ============
--  Comments (replies)
-- ============
create table if not exists public.post_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists post_comments_set_updated_at on public.post_comments;
create trigger post_comments_set_updated_at
before update on public.post_comments
for each row execute function public.set_updated_at();

create index if not exists post_comments_post_created_idx on public.post_comments (post_id, created_at asc);

-- ==================
-- Convenience views
-- ==================
-- Counts used by UI (likes count, comments count)
create or replace view public.posts_with_counts as
select
  p.*, 
  (select count(*) from public.post_likes pl where pl.post_id = p.id) as likes_count,
  (select count(*) from public.post_comments pc where pc.post_id = p.id) as comments_count
from public.posts p;

-- Optional: list posts with their hashtags as an array
create or replace view public.posts_with_hashtags as
select
  p.id,
  p.author_id,
  p.content,
  p.created_at,
  p.updated_at,
  coalesce(array_agg(h.name order by h.name) filter (where h.name is not null), '{}'::text[]) as hashtags
from public.posts p
left join public.post_hashtags ph on ph.post_id = p.id
left join public.hashtags h on h.id = ph.hashtag_id
group by p.id;

-- ==================
-- RLS (Row Level Security)
-- ==================
-- Profiles
alter table public.profiles enable row level security;

drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- Posts
alter table public.posts enable row level security;

drop policy if exists "posts_select_authenticated" on public.posts;
create policy "posts_select_authenticated"
on public.posts for select
to authenticated
using (true);

drop policy if exists "posts_insert_owner" on public.posts;
create policy "posts_insert_owner"
on public.posts for insert
to authenticated
with check (author_id = auth.uid());

drop policy if exists "posts_update_owner" on public.posts;
create policy "posts_update_owner"
on public.posts for update
to authenticated
using (author_id = auth.uid())
with check (author_id = auth.uid());

drop policy if exists "posts_delete_owner" on public.posts;
create policy "posts_delete_owner"
on public.posts for delete
to authenticated
using (author_id = auth.uid());

-- Hashtags
alter table public.hashtags enable row level security;

drop policy if exists "hashtags_select_authenticated" on public.hashtags;
create policy "hashtags_select_authenticated"
on public.hashtags for select
to authenticated
using (true);

-- Allow authenticated users to create new hashtag records (unique index prevents duplicates)
-- If you want stricter control, restrict inserts and only allow via RPC.
drop policy if exists "hashtags_insert_authenticated" on public.hashtags;
create policy "hashtags_insert_authenticated"
on public.hashtags for insert
to authenticated
with check (true);

-- Post hashtags join
alter table public.post_hashtags enable row level security;

drop policy if exists "post_hashtags_select_authenticated" on public.post_hashtags;
create policy "post_hashtags_select_authenticated"
on public.post_hashtags for select
to authenticated
using (true);

-- Only allow attaching hashtags to posts you own
-- (You can loosen this if you want community tagging)
drop policy if exists "post_hashtags_insert_owner" on public.post_hashtags;
create policy "post_hashtags_insert_owner"
on public.post_hashtags for insert
to authenticated
with check (
  exists (
    select 1 from public.posts p
    where p.id = post_id and p.author_id = auth.uid()
  )
);

drop policy if exists "post_hashtags_delete_owner" on public.post_hashtags;
create policy "post_hashtags_delete_owner"
on public.post_hashtags for delete
to authenticated
using (
  exists (
    select 1 from public.posts p
    where p.id = post_id and p.author_id = auth.uid()
  )
);

-- Likes
alter table public.post_likes enable row level security;

drop policy if exists "post_likes_select_authenticated" on public.post_likes;
create policy "post_likes_select_authenticated"
on public.post_likes for select
to authenticated
using (true);

-- Like/unlike only as yourself
-- Note: delete uses USING; insert uses WITH CHECK
drop policy if exists "post_likes_insert_self" on public.post_likes;
create policy "post_likes_insert_self"
on public.post_likes for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "post_likes_delete_self" on public.post_likes;
create policy "post_likes_delete_self"
on public.post_likes for delete
to authenticated
using (user_id = auth.uid());

-- Comments
alter table public.post_comments enable row level security;

drop policy if exists "post_comments_select_authenticated" on public.post_comments;
create policy "post_comments_select_authenticated"
on public.post_comments for select
to authenticated
using (true);

drop policy if exists "post_comments_insert_self" on public.post_comments;
create policy "post_comments_insert_self"
on public.post_comments for insert
to authenticated
with check (author_id = auth.uid());

drop policy if exists "post_comments_update_owner" on public.post_comments;
create policy "post_comments_update_owner"
on public.post_comments for update
to authenticated
using (author_id = auth.uid())
with check (author_id = auth.uid());

drop policy if exists "post_comments_delete_owner" on public.post_comments;
create policy "post_comments_delete_owner"
on public.post_comments for delete
to authenticated
using (author_id = auth.uid());

-- ==================
-- Optional helper RPC: attach hashtags to a post in one call
-- ==================
-- Client can pass an array of tag strings; server upserts hashtags and creates joins.
-- This avoids race conditions and simplifies client code.
create or replace function public.set_post_hashtags(p_post_id uuid, p_tags text[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  t text;
  h_id bigint;
begin
  -- Ensure caller owns the post
  if not exists (select 1 from public.posts where id = p_post_id and author_id = auth.uid()) then
    raise exception 'not allowed';
  end if;

  -- Clear existing
  delete from public.post_hashtags where post_id = p_post_id;

  -- Insert new
  if p_tags is null then
    return;
  end if;

  foreach t in array p_tags loop
    t := btrim(t);
    if t = '' then
      continue;
    end if;

    insert into public.hashtags(name)
    values (t)
    on conflict (lower(name)) do update set name = excluded.name
    returning id into h_id;

    insert into public.post_hashtags(post_id, hashtag_id)
    values (p_post_id, h_id)
    on conflict do nothing;
  end loop;
end;
$$;

-- Allow authenticated users to call the function
revoke all on function public.set_post_hashtags(uuid, text[]) from public;
grant execute on function public.set_post_hashtags(uuid, text[]) to authenticated;
